export const protected_routes: {
  path: string;
  permission_name: string | null;
}[] = [
  { path: "/", permission_name: null },
  { path: "/members/pending", permission_name: "member:edit" },
  { path: "/members/add", permission_name: "member:create" },
  { path: "/members/view", permission_name: "member:view" },
  { path: "/members/history", permission_name: "member:history" },
  { path: "/members/bin", permission_name: "member:delete" },
  { path: "/members", permission_name: "member:view" },
  { path: "/member", permission_name: "member:view" },
  { path: "/users", permission_name: "user:view_list" },
  { path: "/groups", permission_name: "group:view" },
  { path: "/choices", permission_name: "member:view" },
  { path: "/registration", permission_name: "employee:onboard" },
  { path: "/my-activity-logs", permission_name: null },
  { path: "/activity_logs", permission_name: "activity_log:view" },
  { path: "/emails", permission_name: "email:view_logs" },
  { path: "/restaurants/choices", permission_name: "restaurant:menu_edit" },
  { path: "/restaurants/items/add", permission_name: "restaurant:menu_edit" },
  { path: "/restaurants/sales/upload", permission_name: "restaurant:menu_edit" },
  { path: "/restaurants/checkout", permission_name: "restaurant:order_create" },
  { path: "/restaurants", permission_name: "restaurant:view_menu" },
  { path: "/products", permission_name: "product:view" },
  { path: "/promo_codes", permission_name: "promo_code:view" },
  { path: "/upload/sales/lounge", permission_name: "outlet:menu_edit" },
  { path: "/upload/sales/others", permission_name: "member_financial:view_sales" },
  { path: "/upload/sales", permission_name: "member_financial:view_sales" },
  { path: "/mfm/invoices", permission_name: "member_financial:view_invoices" },
  { path: "/mfm/payment_invoice", permission_name: "member_financial:generate_invoice" },
  { path: "/mfm/income", permission_name: "member_financial:view_incomes" },
  { path: "/mfm/income_particulars", permission_name: "member_financial:view_incomes" },
  { path: "/mfm/income_receiving_options", permission_name: "member_financial:view_incomes" },
  { path: "/mfm/payment_options", permission_name: "member_financial:adjust_dues" },
  { path: "/mfm/sales", permission_name: "member_financial:view_sales" },
  { path: "/mfm/transections", permission_name: "member_financial:view_transactions" },
  { path: "/mfm/payments", permission_name: "member_financial:view_payments" },
  { path: "/mfm/view_member_dues", permission_name: "member_financial:view_dues" },
  { path: "/mfm/view_member_accounts", permission_name: "member_financial:view_accounts" },
  { path: "/mfm", permission_name: "member_financial:view_invoices" },
  { path: "/events/venues", permission_name: "event:edit" },
  { path: "/events/fees", permission_name: "event:edit" },
  { path: "/events/media", permission_name: "event:edit" },
  { path: "/events/tickets", permission_name: "event:view" },
  { path: "/events", permission_name: "event:view" },
  { path: "/facilities/create", permission_name: "facility:create" },
  { path: "/facilities", permission_name: "facility:view" },
  { path: "/attendance", permission_name: "attendance:view_records" },
  { path: "/outlets", permission_name: "outlet:view_menu" },
  { path: "/reservations", permission_name: "reservation:view" },
  { path: "/payroll", permission_name: "payroll:view_structures" },
  { path: "/vendors", permission_name: "vendor:view" },
  { path: "/finance", permission_name: "member_financial:view_invoices" },
];
